language: node_js

node_js:
  - "6"

branches:
  only:
  - master

env:
  global:
  - SAUCE_USERNAME=poor-guy
  - SAUCE_ACCESS_KEY=a06fa37e-e337-4985-97bc-72828a4990fd
  - BROWSER_PROVIDER_READY_FILE=/tmp/sauce-connect-ready
  - LOGS_DIR=/tmp/logs
  - SEED_DIR=`pwd`/../jigsaw-seed

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start

install:
  - npm install

before_script:
  - mkdir -p $LOGS_DIR
  - chmod a+x ./build/scripts/sauce_connect_setup.sh
  - ./build/scripts/sauce_connect_setup.sh

script:
  - gulp jigsaw:build-release:clean
  - ng test --code-coverage --watch false
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
  - sh build/scripts/integrate-with-seed.sh
  - sh ./build/scripts/sauce_connect_block.sh
  - cd $SEED_DIR # run e2e in seed directory
  - ng build --prod
  - ng e2e

after_script:
  - sh ./build/scripts/sauce_connect_teardown.sh

sudo: false

